### ISSUE TITLE
Bug: Signup page has inconsistent background

### ISSUE THREAD

**Issue by shardhrv** [StuCo-Official/Frontend#28]
### Current Behaviour
The green in the background does not extend all the way to the bottom and the edge where it ends can be clearly seen:
![image](https://github.com/user-attachments/assets/5989c81f-830a-4b9d-b32e-fbb8c6f637c5)

### Expected Behaviour
The green should completely extend until the bottom of the page.

**Comment by Pawankalyan2023** [comment]
Hey Please close this issue as it has been already resolved
![image](https://github.com/user-attachments/assets/f6f0dc8d-f9e4-4472-a4e1-272ec9370402)
